"""Diagnostic report PDF generation (ReportLab)."""
import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                TableStyle, Image as RLImage)

NAVY = colors.HexColor("#1a237e")
RED = colors.HexColor("#C62828")
AMBER = colors.HexColor("#E65100")


def build_report_pdf(assessment, patient, doctor, heatmap_path=None):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=18 * mm, bottomMargin=16 * mm,
                            leftMargin=18 * mm, rightMargin=18 * mm)
    ss = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=ss["Title"], textColor=NAVY, fontSize=18)
    h2 = ParagraphStyle("h2", parent=ss["Heading2"], textColor=NAVY, fontSize=11,
                        spaceBefore=10, spaceAfter=4)
    body = ParagraphStyle("body", parent=ss["Normal"], fontSize=9.5, leading=14)
    small = ParagraphStyle("small", parent=ss["Normal"], fontSize=8, textColor=colors.grey)

    story = []
    story.append(Paragraph("DermAI — Skin Cancer Assessment Report", h1))
    story.append(Paragraph("Quantum Coders · Faculty of Applied Sciences · "
                           "Rajarata University of Sri Lanka", small))
    story.append(Paragraph(
        f"Report #RPT-{assessment.id:05d} &nbsp;·&nbsp; "
        f"{datetime.utcnow():%d %b %Y %H:%M} UTC &nbsp;·&nbsp; "
        f"Inference mode: <b>{(assessment.mode or 'rule').upper()}</b>", small))
    story.append(Spacer(1, 8))

    # patient
    story.append(Paragraph("Patient Information", h2))
    pt = [
        ["Name", f"{patient.first_name or ''} {patient.last_name or ''}".strip() or "—",
         "Age / Gender", f"{patient.age or '—'} / {patient.gender or '—'}"],
        ["Fitzpatrick", patient.fitzpatrick or "—", "Lesion Location", patient.lesion_location or "—"],
        ["Duration (wk)", str(patient.duration_weeks or "—"), "Attending Doctor",
         f"{doctor.name} ({doctor.slmc_no or '—'})"],
    ]
    story.append(_grid(pt))

    # probabilities
    story.append(Paragraph("AI Cancer Classification Probabilities", h2))
    probs = [("Melanoma", assessment.prob_mel), ("BCC", assessment.prob_bcc),
             ("SCC", assessment.prob_scc), ("MCC", assessment.prob_mcc)]
    rows = [["Cancer type", "Probability"]]
    for name, val in probs:
        rows.append([name, f"{(val or 0):.1f}%"])
    t = Table(rows, colWidths=[90 * mm, 80 * mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 9.5),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#CFD8DC")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F0F4FF")]),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(t)
    story.append(Spacer(1, 6))

    summary = [
        ["Predicted type", assessment.predicted_type or "—", "Confidence",
         f"{(assessment.confidence or 0):.1f}%"],
        ["Predicted stage", assessment.stage or "—", "Urgency", assessment.urgency or "—"],
        ["Uncertain (<50%)", "Yes" if assessment.uncertain else "No", "Mode",
         (assessment.mode or "rule").upper()],
    ]
    story.append(_grid(summary))

    if heatmap_path:
        try:
            story.append(Paragraph("Explainability (Grad-CAM / saliency)", h2))
            story.append(RLImage(heatmap_path, width=60 * mm, height=60 * mm))
        except Exception:
            pass

    story.append(Paragraph("Clinical Recommendation", h2))
    story.append(Paragraph(
        f"AI analysis indicates the highest risk for <b>{assessment.predicted_type}</b> "
        f"({(assessment.confidence or 0):.1f}% confidence, {assessment.stage} stage). "
        f"Urgency: <b>{assessment.urgency}</b>. A biopsy (histopathology) is recommended "
        "to confirm the diagnosis and determine the treatment pathway.", body))

    story.append(Spacer(1, 6))
    story.append(Paragraph("Mandatory Disclaimer", h2))
    story.append(Paragraph(
        "This report is generated by an AI clinical decision-support system for use by "
        "licensed medical professionals only. No skin cancer can be confirmed without "
        "histopathology (biopsy) and specialist evaluation. All probabilities are estimates "
        "and do not constitute a definitive diagnosis.",
        ParagraphStyle("disc", parent=body, textColor=RED, fontSize=8.5)))

    doc.build(story)
    buf.seek(0)
    return buf


def _grid(data):
    t = Table(data, colWidths=[35 * mm, 50 * mm, 35 * mm, 50 * mm])
    t.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#E3F2FD")),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F0F4FF")),
        ("BACKGROUND", (2, 0), (2, -1), colors.HexColor("#F0F4FF")),
        ("TEXTCOLOR", (0, 0), (0, -1), NAVY),
        ("TEXTCOLOR", (2, 0), (2, -1), NAVY),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("PADDING", (0, 0), (-1, -1), 5),
    ]))
    return t
